"""empty message

Revision ID: 1b72815d2cb2
Revises: 6b81c0037d30
Create Date: 2018-09-19 09:59:12.248840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b72815d2cb2'
down_revision = '6b81c0037d30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sacco', sa.Column('roles_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sacco', 'roles', ['roles_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sacco', type_='foreignkey')
    op.drop_column('sacco', 'roles_id')
    # ### end Alembic commands ###
