"""empty message

Revision ID: 86b9204c072a
Revises: 1b72815d2cb2
Create Date: 2018-09-19 10:16:10.563617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86b9204c072a'
down_revision = '1b72815d2cb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fares', sa.Column('fares', sa.Integer(), nullable=True))
    op.drop_column('fares', 'fare')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fares', sa.Column('fare', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fares', 'fares')
    # ### end Alembic commands ###
