"""Initial Migration

Revision ID: 90980b4151f6
Revises: 
Create Date: 2018-09-19 21:55:19.442297

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90980b4151f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sacco',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('sacconame', sa.String(length=255), nullable=True),
    sa.Column('password_secure', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('route', sa.String(length=255), nullable=True),
    sa.Column('roles_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['roles_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sacco_email'), 'sacco', ['email'], unique=True)
    op.create_index(op.f('ix_sacco_sacconame'), 'sacco', ['sacconame'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('password_secure', sa.String(length=255), nullable=True),
    sa.Column('phone_number', sa.Integer(), nullable=True),
    sa.Column('role', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('fares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fare', sa.Integer(), nullable=True),
    sa.Column('sacco_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['sacco_id'], ['sacco.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fares')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_sacco_sacconame'), table_name='sacco')
    op.drop_index(op.f('ix_sacco_email'), table_name='sacco')
    op.drop_table('sacco')
    op.drop_table('roles')
    # ### end Alembic commands ###
