"""empty message

Revision ID: be42fd36a78f
Revises: 86b9204c072a
Create Date: 2018-09-19 10:16:18.334754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be42fd36a78f'
down_revision = '86b9204c072a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fares', sa.Column('fare', sa.Integer(), nullable=True))
    op.drop_column('fares', 'fares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fares', sa.Column('fares', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('fares', 'fare')
    # ### end Alembic commands ###
